# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbxqjbUQdJZ3VUvqHosYH6gSw4iBdrbU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

df = pd.read_csv("spam.csv",encoding="latin")
df.head()

df.ndim

df.shape

df.size

df.isna().sum()

df.info()

df.head()

df.tail()

df label_num():
   df["label_num"].value_counts().plot(kind="bar",figsize=(12,6))
   plt.xticks(np.arange(2), ('Non spam', 'spam'),rotation=0);

import re
corpus = []
length = len(df)

df text():
  for i in range (0,length):
    text = re.sub("[^a-zA-Z0-9]"," ",df["text"][i])
    text = text.lower()
    text = text.split()
    pe = PorterStemmer()
    stopword = stopwords.words("english")
    text = [pe.stem(word)for word in text if not word in set (stopword)]
    text = " ". join(text)
    corpus.append(text)

corpus

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=35000)
X = cv.fit_transform(corpus).toarray()

y = pd.get_dummies(df['label'])
y = y.iloc[:, 1].values

import pickle
pickle.dump(cv, open('cv.pK1', 'wb'))

from sklearn.model_selection import train_test_split
x_train,x_test,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

from sklearn.naive_bayes import MultinominalNB
model = MultinominalNB()

model.fit(x_train, y_train)